root: true

env:
  mocha: true

extends:
  - xo-space/esnext

rules:
  capitalized-comments:
    - off
  comma-dangle:
    - error
    - always-multiline
  curly:
    - error
    - multi-or-nest
  keyword-spacing:
    - error
    - overrides:
        catch:
          after: false
        for:
          after: false
        if:
          after: false
        switch:
          after: false
        while:
          after: false
  new-cap:
    - error
    - capIsNew: false
  no-return-assign:
    - error
    - except-parens
  no-unused-expressions:
    - error
    - allowTernary: true
  no-warning-comments:
    - off
  object-curly-spacing:
    - error
    - always
  one-var: off
  quotes:
    - error
    - single
  space-before-function-paren:
    - error
    - never

overrides:
  files:
    - '*.spec.js'
    - '*.spec.int.js'
  rules:
    no-unused-expressions: off
