image: node:11-alpine

stages:
  - build
  - deploy

test:
  stage: build
  script:
    - npm install
    - npm run test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/main.js

examine:
  stage: deploy
  script: ls -al
