image: node:11-alpine

stages:
  - build
  - publish
  - deploy

test:
  stage: build
  script:
    - npm install
    - npm run test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/main.js

docker:
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
  script:
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - docker build -t "kitsunesystem/kitsune:$CI_COMMIT_SHA" .
    - docker push "kitsunesystem/kitsune:$CI_COMMIT_SHA"

kubernetes:
  stage: deploy
  image:
    name: lachlanevenson/k8s-kubectl
    entrypoint: [""]
  environment:
    name: dev
    url: http://35.202.123.173
  script:
    - sed "s/TAG/$CI_COMMIT_SHA/" kube.yml | kubectl apply -f -
