image: node:11-alpine

stages:
  - build
  - deploy

test:
  stage: build
  script:
    - npm install
    - npm run test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/main.js

docker:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  variables:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_DRIVER: overlay2
  script:
    - env
    - docker login --username "$USER" --password "$PASSWORD"
    - docker build -t kitsunesystem/kitsune:test .
    - docker push kitsunesystem/kitsune:test
